export enum FieldType {
  NONE = 'none',
  TEXT = 'text',
  PASSWORD = 'password',
  TEXTAREA = 'textarea',
  DATE = 'date',
  DATETIME = 'datetime',
  NUMBER = 'number',
  CURRENCY = 'currency',
  SELECT = 'select',
  ENUM = 'enum',
  ENTITY = 'entity',
  RADIO = 'radio',
  SWITCH = 'switch',
  CHECKBOX = 'checkbox',
  FILE = 'file',
  TAGS = 'tags',
  HTML = 'html',
}
